# LIST
- list.append(x)
- list.extend(iterable)
- list.insert(i, x)
- list.remove(x)
- list.pop([i])
- list.clear()
- list.index(x[, start[, end]])
- list.count(x)
- list.sort(key=None, reverse=False)
- list.reverse()
- list.copy()

__For more stuffs about [Lists](https://docs.python.org/3/tutorial/datastructures.html) refer to the given link__


In [1]:
l1 = [1, 2, 3, 1, 4, 2, 2, 5, 2]
l1

[1, 2, 3, 1, 4, 2, 2, 5, 2]

In [2]:
l1.append(15) # add 15 at the end of l1
l1

[1, 2, 3, 1, 4, 2, 2, 5, 2, 15]

In [3]:
l2 = [16, 17, 16, 18, 20]
l1.extend(l2) # adds the list l2 to l1
l1

[1, 2, 3, 1, 4, 2, 2, 5, 2, 15, 16, 17, 16, 18, 20]

In [4]:
l1.insert(3, 8) # at position 3 insert the value 8
l1

[1, 2, 3, 8, 1, 4, 2, 2, 5, 2, 15, 16, 17, 16, 18, 20]

In [5]:
l1.remove(2) # removes the first item in the list whose value is equal to 2
l1

[1, 3, 8, 1, 4, 2, 2, 5, 2, 15, 16, 17, 16, 18, 20]

In [6]:
l1.pop() # remove the last element
l1

[1, 3, 8, 1, 4, 2, 2, 5, 2, 15, 16, 17, 16, 18]

In [7]:
l2.clear() # clears the list
l2

[]

In [8]:
l1.index(8) # index of first element with value equal to 8

2

In [9]:
l1.count(2) # counts the number of times 2 is in present in the list

3

In [10]:
l1.sort()
l1

[1, 1, 2, 2, 2, 3, 4, 5, 8, 15, 16, 16, 17, 18]

In [11]:
l1.reverse()
l1

[18, 17, 16, 16, 15, 8, 5, 4, 3, 2, 2, 2, 1, 1]

In [12]:
l3 = l1.copy()
l3

[18, 17, 16, 16, 15, 8, 5, 4, 3, 2, 2, 2, 1, 1]

***
# Installing Numpy

The only prerequisite for NumPy is Python itself. If you don’t have Python yet and want the simplest way to get started, we recommend you use the Anaconda Distribution - it includes Python, NumPy, and other commonly used packages for scientific computing and data science.

## CONDA
conda install numpy<br>
To Download [Anaconda](https://www.anaconda.com/products/individual) follow this link

## PIP
pip install numpy<br>
To Download [pip](https://pypi.org/project/pip-download/#files) follow this link

__Refer to the Official website of [Numpy](https://numpy.org/doc/stable/index.html) for more details__
***

## Import Numpy

In [13]:
import numpy as np

## Numpy Array

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
a[0]

array([1, 2, 3])

In [16]:
print(np.array([1,2]))

[1 2]


In [17]:
c = [1,2,3,4,5,6,7,8]
c

[1, 2, 3, 4, 5, 6, 7, 8]

In [18]:
type(c)

list

In [19]:
c = np.array(c)
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
type(c)

numpy.ndarray

In [21]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.empty([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## np.arange()

To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
b.dtype

dtype('int32')

In [27]:
type(b)

numpy.ndarray

In [28]:
np.arange(10, 50, 5) # An array from 10 to 50 with step size 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [29]:
np.arange(1, 3, 0.3) # Arguments can also take float value

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

## np.concatenate

In [30]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

## ndarray.ndim, ndarray.size, ndarray.shape

In [31]:
arr = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])
arr

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [32]:
arr.ndim # Number of Axes

3

In [33]:
arr.size # Total number of elements of the array

24

In [34]:
arr.shape # Number of elements stored along each dimension of the array

(3, 2, 4)

## ndarray.reshape

In [35]:
arr.reshape(6,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

## Uses of Numpy

In [36]:
# 1D array to 2D array
a = np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [37]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
b = np.expand_dims(a, axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [39]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
b = a[a>5]
b

array([ 6,  7,  8,  9, 10, 11, 12])

In [41]:
d2 = a[a%2 == 0]
d2

array([ 2,  4,  6,  8, 10, 12])

## Easy Array Operations

In [42]:
data = np.array([[3, 4], [5, 6], [2,7]])
ones = np.ones(2, dtype=int)

In [43]:
print("Data", data)

Data [[3 4]
 [5 6]
 [2 7]]


In [44]:
print("Ones", ones)

Ones [1 1]


In [45]:
data * 3 # Each element gets multiplied with 3

array([[ 9, 12],
       [15, 18],
       [ 6, 21]])

In [46]:
data + 3 # Each element is added with 3

array([[ 6,  7],
       [ 8,  9],
       [ 5, 10]])

In [47]:
data.shape

(3, 2)

In [48]:
ones.shape

(2,)

In [49]:
data + ones

array([[4, 5],
       [6, 7],
       [3, 8]])

In [50]:
data - ones

array([[2, 3],
       [4, 5],
       [1, 6]])

In [51]:
data * data # Element wise product

array([[ 9, 16],
       [25, 36],
       [ 4, 49]])

In [52]:
data / data

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [53]:
twos = ones * 2
twos

array([2, 2])

In [54]:
np.dot(data,twos) # Matrix Multiplication between data and twos

array([14, 22, 18])

In [55]:
data.dot(twos)

array([14, 22, 18])

In [56]:
a = np.array([2,3,5,6])
a

array([2, 3, 5, 6])

In [57]:
b = a .reshape(2,2)
b

array([[2, 3],
       [5, 6]])

In [58]:
b.sum(axis = 0) # Row wise Sum

array([7, 9])

In [59]:
b.sum(axis = 1) # Column wise Sum

array([ 5, 11])

In [60]:
data

array([[3, 4],
       [5, 6],
       [2, 7]])

In [61]:
data.max() # Maximum of all elements in array

7

In [62]:
data.min() # Minimum of all elements in array

2

In [63]:
data.max(axis = 0) # Column wise Max element

array([5, 7])

In [64]:
data.max(axis = 1) # Row wise Max element

array([4, 6, 7])

In [65]:
np.random.rand(4,3) # Creating and Array of random numbers

array([[0.47148593, 0.25217085, 0.2960618 ],
       [0.94488368, 0.4770487 , 0.95173312],
       [0.5629355 , 0.13512283, 0.95840284],
       [0.78787593, 0.9594214 , 0.1607808 ]])

## Universal Functions

In [66]:
p = np.arange(4)
p

array([0, 1, 2, 3])

In [67]:
np.exp(p) # Exponential value of each element

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [68]:
np.sqrt(p) # Square root of each element

array([0.        , 1.        , 1.41421356, 1.73205081])

In [69]:
p ** 3 # Cube of each element

array([ 0,  1,  8, 27], dtype=int32)

In [70]:
x = np.arange(25)

In [71]:
x = x.reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
for row in x:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [73]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
y = np.random.rand(6,3)
y

array([[0.56701392, 0.31342415, 0.36098435],
       [0.36109395, 0.18747023, 0.82989164],
       [0.40708221, 0.0957976 , 0.43147585],
       [0.17004759, 0.55048244, 0.85752935],
       [0.12037371, 0.55614493, 0.65908158],
       [0.48789775, 0.76018679, 0.00640938]])

In [75]:
y = y*100
y

array([[56.7013924 , 31.34241476, 36.09843514],
       [36.10939513, 18.7470231 , 82.98916438],
       [40.70822109,  9.57975982, 43.1475853 ],
       [17.00475897, 55.04824386, 85.75293477],
       [12.03737094, 55.61449269, 65.90815845],
       [48.78977511, 76.01867906,  0.64093847]])

In [76]:
y = np.floor(y) # Floor Values of each elements
y

array([[56., 31., 36.],
       [36., 18., 82.],
       [40.,  9., 43.],
       [17., 55., 85.],
       [12., 55., 65.],
       [48., 76.,  0.]])

***
# For any more knowledge and learning please go to the Given Link
# [Numpy](https://numpy.org/)
***