# LIST
- list.append(x)
- list.extend(iterable)
- list.insert(i, x)
- list.remove(x)
- list.pop([i])
- list.clear()
- list.index(x[, start[, end]])
- list.count(x)
- list.sort(key=None, reverse=False)
- list.reverse()
- list.copy()

In [55]:
l1 = [1, 2, 3, 1, 4, 2, 2, 5, 2]
l1

[1, 2, 3, 1, 4, 2, 2, 5, 2]

In [56]:
l1.append(15) # add 15 at the end of l1
l1

[1, 2, 3, 1, 4, 2, 2, 5, 2, 15]

In [57]:
l2 = [16, 17, 16, 18, 20]
l1.extend(l2) # adds the list l2 to l1
l1

[1, 2, 3, 1, 4, 2, 2, 5, 2, 15, 16, 17, 16, 18, 20]

In [58]:
l1.insert(3, 8) # at position 3 insert the value 8
l1

[1, 2, 3, 8, 1, 4, 2, 2, 5, 2, 15, 16, 17, 16, 18, 20]

In [59]:
l1.remove(2) # removes the first item in the list whose value is equal to 2
l1

[1, 3, 8, 1, 4, 2, 2, 5, 2, 15, 16, 17, 16, 18, 20]

In [60]:
l1.pop() # remove the last element
l1

[1, 3, 8, 1, 4, 2, 2, 5, 2, 15, 16, 17, 16, 18]

In [61]:
l2.clear() # clears the list
l2

[]

In [62]:
l1.index(8) # index of first element with value equal to 8

2

In [64]:
l1.count(2) # counts the number of times 2 is in present in the list

3

In [66]:
l1.sort()
l1

[1, 1, 2, 2, 2, 3, 4, 5, 8, 15, 16, 16, 17, 18]

In [69]:
l1.reverse()
l1

[18, 17, 16, 16, 15, 8, 5, 4, 3, 2, 2, 2, 1, 1]

In [70]:
l3 = l1.copy()
l3

[18, 17, 16, 16, 15, 8, 5, 4, 3, 2, 2, 2, 1, 1]

# Installing Numpy

The only prerequisite for NumPy is Python itself. If you don’t have Python yet and want the simplest way to get started, we recommend you use the Anaconda Distribution - it includes Python, NumPy, and other commonly used packages for scientific computing and data science.

## CONDA
conda install numpy<br>
To Download [Anaconda](https://www.anaconda.com/products/individual) follow this link

## PIP
pip install numpy<br>
To Download [pip](https://pypi.org/project/pip-download/#files) follow this link

## Import Numpy

In [5]:
import numpy as np

## Numpy Array

In [46]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
a[0]

array([1, 2, 3])

In [7]:
print(np.array([1,2]))

[1 2]


In [30]:
c = [1,2,3,4,5,6,7,8]
c

[1, 2, 3, 4, 5, 6, 7, 8]

In [31]:
type(c)

list

In [33]:
c = np.array(c)
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
type(c)

numpy.ndarray

In [72]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
np.empty([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## np.arange()

To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
b.dtype

dtype('int32')

In [84]:
type(b)

numpy.ndarray

In [42]:
np.arange(10, 50, 5) # An array from 10 to 50 with step size 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [45]:
np.arange(1, 3, 0.3) # Arguments can also take float value

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

## np.concatenate

In [75]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

## ndarray.ndim, ndarray.size, ndarray.shape

In [86]:
arr = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])
arr

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [87]:
arr.ndim # Number of Axes

3

In [88]:
arr.size # Total number of elements of the array

24

In [89]:
arr.shape # Number of elements stored along each dimension of the array

(3, 2, 4)

## ndarray.reshape

In [90]:
arr.reshape(6,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

## Uses of Numpy